
<!DOCTYPE html>
<head>
	<link href="/skin/css/mainstyles.css" rel="stylesheet" />	
	<link href="https://fonts.googleapis.com/css2?family=Archivo+Narrow:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"> 
</head>
<body>
	<header class="home-header">
		<div class="head-flex-wrapper">
			<div class="head-left">
				<img class="head-logo" src="/skin/images/Logo.png" />
			</div>
			<div class="head-mid">

			</div>
			<div class="head-right">

			</div>
		</div>
		
	</header>
	<main>
		<div class="main-top">

		</div>
	
	</main>
	<footer>

	</footer>
</body>


